services:
  application:
    build:
      context: .
      dockerfile: Dockerfile
    image: thomasve/worldengine:0.1.3
    container_name: "worldengine"
    command: ["uvicorn", "main:app", "--reload", "--proxy-headers", "--host", "0.0.0.0", "--port", "${PORT}"]
    volumes:
      - "./${APPLICATION_DIR}:/${APPLICATION_DIR}"
    ports:
      - "${PORT}:${PORT}"
    networks:
      - worldengine

networks:
  worldengine:
    external: true
